export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'eutils',
        'pubmed-xml',
        'pubmed',
        'jats',
        'pmc',
        'id-converter',
        'pubtator',
        'mesh',
        'cite',
        'mcp',
        'rate-limiter',
        'xml',
        'fasta',
        'datasets',
        'blast',
        'snp',
        'clinvar',
        'pubchem',
        'genbank',
        'protein',
        'nucleotide',
        'omim',
        'medgen',
        'gtr',
        'geo',
        'dbvar',
        'sra',
        'structure',
        'cdd',
        'books',
        'nlm-catalog',
        'workspace',
      ],
    ],
  },
};
